DROP TABLE EMPLOYEE_JOB_HISTORY;

CREATE TABLE EMPLOYEE_JOB_HISTORY ( 
ID INT PRIMARY KEY AUTO_INCREMENT, 
EMP_ID INT NOT NULL,
DESIGNATION VARCHAR(50) NOT NULL,
DEPARTMENT VARCHAR(50) NOT NULL,
DATE_OF_JOINING DATE NOT NULL,
END_OF_RELEVING DATE,
CONSTRAINT EMP_ID_UQ UNIQUE ( EMP_ID),
CONSTRAINT EMPLOYEE_JOB_HISTORY_EMP_ID_FK FOREIGN KEY ( EMP_ID)
REFERENCES EMPLOYEES( ID)
);


INSERT INTO EMPLOYEE_JOB_HISTORY ( EMP_ID , DESIGNATION,DEPARTMENT,DATE_OF_JOINING,END_OF_RELEVING)
				VALUES ( 1, "Software Engineer","Developement","2015-11-25","2017-11-25");

SELECT * FROM EMPLOYEE_JOB_HISTORY;


