DROP TABLE ROLE;

CREATE TABLE ROLE (
ID INT PRIMARY KEY AUTO_INCREMENT,
ROLE_CODE VARCHAR(10) NOT NULL,
ROLE_NAME VARCHAR(100) NOT NULL,
LEVEL INT NOT NULL,
ACTIVE TINYINT DEFAULT 1,
CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT ROLE_CODE_UQ UNIQUE ( ROLE_CODE),
CONSTRAINT ROLE_NAME_UQ UNIQUE ( ROLE_NAME)
);

INSERT INTO ROLE ( ROLE_CODE, ROLE_NAME, LEVEL)
VALUES 
('SP001', 'System Admin', 11),
('SP002', 'Managing Director', 10),
('SP003', 'Product Lead', 9),
('SP004', 'Techniqal Lead',8),
('SP005', 'Developer', 7);


SELECT * FROM ROLE;