DROP TABLE ROLE_LEAVES;

CREATE TABLE ROLE_LEAVES
(
ID INT PRIMARY KEY AUTO_INCREMENT,
ROLE_ID INT NOT NULL,
CASUAL_LEAVE INT NOT NULL,
SICK_LEAVE INT NOT NULL,
PAID_LEAVE INT NOT NULL,
MATERNITY_LEAVE INT NOT NULL,
PATERNITY_LEAVE INT NOT NULL,
PRIVILEGED_LEAVE INT NOT NULL,
ACTIVE TINYINT DEFAULT 1,
CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT LEAVE_ROLE_ID_FK FOREIGN KEY ( ROLE_ID) REFERENCES ROLE( ID),
CONSTRAINT LEAVE_ROLE_ID_UQ UNIQUE ( ROLE_ID)
);


INSERT INTO ROLE_LEAVES ( ROLE_ID, CASUAL_LEAVE, SICK_LEAVE, PAID_LEAVE, MATERNITY_LEAVE, PATERNITY_LEAVE, PRIVILEGED_LEAVE )
VALUES 
( 5, 3,12,12,90, 5,12),
( 4, 3,12,12,90, 5,12),
( 3, 18,12,12,90, 5,12),
( 2, 18,18,18,90, 5,18);

SELECT * FROM ROLE_LEAVES;
