DROP TABLE EMPLOYEE_LEAVE_DETAILS;

CREATE TABLE EMPLOYEE_LEAVE_DETAILS
(
ID INT PRIMARY KEY AUTO_INCREMENT,
EMP_ID INT NOT NULL,
FROM_DATE DATE NOT NULL,
TO_DATE DATE NOT NULL,
NO_OF_DAYS INT NOT NULL,
LEAVE_TYPE INT NOT NULL,
APPLIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
STATUS_ID INT NOT NULL,
APPROVED_DATE DATETIME ,
MODIFIED_BY INT,
MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
CONSTRAINT LEAVE_DETAILS_STATUS_ID_FK FOREIGN KEY ( STATUS_ID) REFERENCES LEAVE_STATUS(ID),
CONSTRAINT LEAVE_DETAILS_EMP_ID_FK FOREIGN KEY ( EMP_ID) REFERENCES EMPLOYEES(ID),
CONSTRAINT LEAVE_DETAILS_MODIFIED_BY_FK FOREIGN KEY ( MODIFIED_BY ) REFERENCES EMPLOYEES(ID),
CONSTRAINT LEAVE_DETAILS_LEAVE_TYPE_FK FOREIGN KEY ( LEAVE_TYPE) REFERENCES LEAVE_TYPES( ID )
);

INSERT INTO EMPLOYEE_LEAVE_DETAILS 
( EMP_ID , FROM_DATE, TO_DATE, NO_OF_DAYS, LEAVE_TYPE, APPLIED_DATE , STATUS_ID )
VALUES
( 1, '2017-01-01', '2017-01-01', 1 , 1, '2016-12-31', 1);


SELECT * FROM EMPLOYEE_LEAVE_DETAILS;




