DROP TABLE EMPLOYEE_HIERARCHY;

CREATE TABLE EMPLOYEE_HIERARCHY(ID INT PRIMARY KEY AUTO_INCREMENT,EMP_ID INT NOT NULL,MGR_ID INT NOT NULL,
CONSTRAINT EMPLOYEE_HIERARCHY_EMP_ID_FK FOREIGN KEY ( EMP_ID) REFERENCES EMPLOYEES(ID));

INSERT INTO EMPLOYEE_HIERARCHY ( EMP_ID, MGR_ID)
VALUES 
( 1, 6),
( 6, 3),
( 2, 4),
( 4, 3);

SELECT * FROM EMPLOYEE_HIERARCHY ;