DROP TABLE TAX_DECLARATION;

CREATE TABLE TAX_DECLARATION( TAX_ID INT PRIMARY KEY AUTO_INCREMENT,
EMP_ID INT NOT NULL,
PAN_NUMBER VARCHAR(10) NOT NULL,
HOUSE_RENT FLOAT NOT NULL,
HOUSE_OWNER_NAME VARCHAR(100) NOT NULL,
MEDICAL_BILLS FLOAT NOT NULL,
EPF_VPF_CONTRIBUTION FLOAT NOT NULL,
PPF FLOAT NOT NULL,
SENIOR_CITITIZEN FLOAT NOT NULL,
NSC FLOAT NOT NULL,
TAX_SAVING_FD FLOAT NOT NULL,
TAX_SAVING_BONDS FLOAT NOT NULL,
ELSS FLOAT NOT NULL,
LIFE_INSURANCE FLOAT NOT NULL,
PENSION_PLAN FLOAT NOT NULL,
CENTRAL_GOVT_PENSION_PLAN FLOAT NOT NULL,
HOUSING_LOAN FLOAT NOT NULL,
SUKANYA_SAMRIDDHI_ACCOUNT FLOAT NOT NULL,
STAMP_DUTY_CHARGES FLOAT NOT NULL,
TUITION_FEES FLOAT NOT NULL,     
ADDITIONAL_DEDUCTION FLOAT NOT NULL,
DEDUCTION_RGESS FLOAT NOT NULL, 
MEDICAL_INSURANCE_SELF FLOAT NOT NULL,
MEDICAL_INSURANCE_PARENTS FLOAT NOT NULL,
EDUCATION_LOAN FLOAT NOT NULL,
MEDICAL_TREATMENT FLOAT NOT NULL,
EXPENDITURE_MEDICAL_TREATMENT FLOAT NOT NULL,
DONATION_APPROVED_FUNDS FLOAT NOT NULL,
PHYSICALLY_DISABLED_ASSESSE FLOAT NOT NULL,
CONSTRAINT TAX_DECLARATION_EMP_ID_FK FOREIGN KEY ( EMP_ID) REFERENCES EMPLOYEES(ID));



SELECT * FROM TAX_DECLARATION ;